module.exports ={
    //删除状态
    DELETE_FLAG:{
        YES:1,
        NO:0
    },
    //用户id 默认值
    USER_ID:0,
    NUMBER:{
        ZERO:0,
        ONE:1,
        TWO:2,
        THREE:3,
        ONE_HUNDRED:100,
    },
    SELECTED:{
        YES:1,
        NO:0
    },
    PRODUCT_STATUS:{
        ENABLE:1,
        DISABLE:0
    },
    CART_UPDATE_TYPE:{
        ADD:1,
        SUB:0
    },
    ORDER_STATUS:{
        //已取消
        CANCEL:0,
        //未付款
        UN_PAY:10,
        //已付款
        PAY:20,
        //已发货
        SEND:40,
        //交易成功
        SUCCESS:50
    },
    PAY_TYPE:{
        //在线支付
        ONLINE:1
    },
}